# Generated by Django 3.0.7 on 2020-06-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.TextField()),
                ('gu', models.TextField()),
                ('dong', models.TextField()),
            ],
        ),
    ]
