# Generated by Django 3.0.7 on 2020-06-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
